# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0002_auto_20160818_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='sy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='sz',
            field=models.IntegerField(default=0),
        ),
    ]
