# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0003_auto_20160818_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
